name: Calc Action
inputs:
  x:
    default: 0
  y:
    default: 0
outputs:
  plus:
    value: ${{ steps.plus.outputs.result }}
  minus:
    value: ${{ steps.minus.outputs.result }}
runs:
  using: "composite"
  steps:
    - run: echo "Hi, I'm a calculator action!"
      shell: bash
    - run: echo "x = ${{ inputs.x }}, y = ${{ inputs.y }}"
      shell: bash
